// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (
    role_id,
    permission_id
)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id)
DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (
    user_id,
    role_id
)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id)
DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const getUserAuthorization = `-- name: GetUserAuthorization :one
SELECT
    u.status,
    COALESCE(
        (
            SELECT array_agg(DISTINCT r.name)
            FROM roles r
            INNER JOIN user_roles ur ON ur.role_id = r.id
            WHERE ur.user_id = u.id
        ),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        (
            SELECT array_agg(DISTINCT p.name)
            FROM permissions p
            INNER JOIN role_permissions rp ON rp.permission_id = p.id
            INNER JOIN user_roles ur ON ur.role_id = rp.role_id
            WHERE ur.user_id = u.id
        ),
        ARRAY[]::text[]
    )::text[] AS permissions
FROM users u
WHERE u.id = $1
`

type GetUserAuthorizationRow struct {
	Status      string   `json:"status"`
	Roles       []string `json:"roles"`
	Permissions []string `json:"permissions"`
}

func (q *Queries) GetUserAuthorization(ctx context.Context, id uuid.UUID) (GetUserAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthorization, id)
	var i GetUserAuthorizationRow
	err := row.Scan(&i.Status, &i.Roles, &i.Permissions)
	return i, err
}

const listUserPermissions = `-- name: ListUserPermissions :many
SELECT DISTINCT
    p.id,
    p.name
FROM permissions p
INNER JOIN role_permissions rp
    ON rp.permission_id = p.id
INNER JOIN user_roles ur
    ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
ORDER BY p.name
`

type ListUserPermissionsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListUserPermissions(ctx context.Context, userID uuid.UUID) ([]ListUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPermissionsRow{}
	for rows.Next() {
		var i ListUserPermissionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT
    r.id,
    r.name
FROM roles r
INNER JOIN user_roles ur
    ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

type ListUserRolesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]ListUserRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRolesRow{}
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1
  AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1
  AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}
