// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package db

import (
	"context"
	"net"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthSession = `-- name: ConsumeAuthSession :one
UPDATE auth_sessions
SET
    consumed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > NOW()
  AND refresh_token_hash = $2
RETURNING
    id,
    user_id,
    family_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    consumed_at,
    revoked_at,
    revocation_reason,
    created_at,
    updated_at
`

type ConsumeAuthSessionParams struct {
	ID                      uuid.UUID `json:"id"`
	CurrentRefreshTokenHash string    `json:"current_refresh_token_hash"`
}

type ConsumeAuthSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	FamilyID         uuid.UUID          `json:"family_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        net.IP             `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason *string            `json:"revocation_reason"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

func (q *Queries) ConsumeAuthSession(ctx context.Context, arg ConsumeAuthSessionParams) (ConsumeAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, consumeAuthSession, arg.ID, arg.CurrentRefreshTokenHash)
	var i ConsumeAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    id,
    user_id,
    family_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    user_id,
    family_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    consumed_at,
    revoked_at,
    revocation_reason,
    created_at,
    updated_at
`

type CreateAuthSessionParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	FamilyID         uuid.UUID `json:"family_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	UserAgent        *string   `json:"user_agent"`
	IpAddress        net.IP    `json:"ip_address"`
	ExpiresAt        time.Time `json:"expires_at"`
}

type CreateAuthSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	FamilyID         uuid.UUID          `json:"family_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        net.IP             `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason *string            `json:"revocation_reason"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (CreateAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i CreateAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAuthSessionByID = `-- name: GetActiveAuthSessionByID :one
SELECT
    id,
    user_id,
    family_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    consumed_at,
    revoked_at,
    revocation_reason,
    created_at,
    updated_at
FROM auth_sessions
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type GetActiveAuthSessionByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	FamilyID         uuid.UUID          `json:"family_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        net.IP             `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason *string            `json:"revocation_reason"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

func (q *Queries) GetActiveAuthSessionByID(ctx context.Context, id uuid.UUID) (GetActiveAuthSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveAuthSessionByID, id)
	var i GetActiveAuthSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
SELECT
    id,
    user_id,
    family_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    consumed_at,
    revoked_at,
    revocation_reason,
    created_at,
    updated_at
FROM auth_sessions
WHERE id = $1
LIMIT 1
`

type GetAuthSessionByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	FamilyID         uuid.UUID          `json:"family_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        net.IP             `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason *string            `json:"revocation_reason"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

func (q *Queries) GetAuthSessionByID(ctx context.Context, id uuid.UUID) (GetAuthSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, id)
	var i GetAuthSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthSessionsByUserID = `-- name: ListAuthSessionsByUserID :many
SELECT
    id,
    user_id,
    family_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    consumed_at,
    revoked_at,
    revocation_reason,
    created_at,
    updated_at
FROM auth_sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAuthSessionsByUserIDRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	FamilyID         uuid.UUID          `json:"family_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        net.IP             `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason *string            `json:"revocation_reason"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

func (q *Queries) ListAuthSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]ListAuthSessionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listAuthSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthSessionsByUserIDRow{}
	for rows.Next() {
		var i ListAuthSessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSession = `-- name: RevokeAuthSession :one
UPDATE auth_sessions
SET
    revoked_at = NOW(),
    revocation_reason = $2,
    updated_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING
    id,
    user_id,
    family_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    consumed_at,
    revoked_at,
    revocation_reason,
    created_at,
    updated_at
`

type RevokeAuthSessionParams struct {
	ID               uuid.UUID `json:"id"`
	RevocationReason *string   `json:"revocation_reason"`
}

type RevokeAuthSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	FamilyID         uuid.UUID          `json:"family_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        net.IP             `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason *string            `json:"revocation_reason"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (RevokeAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeAuthSession, arg.ID, arg.RevocationReason)
	var i RevokeAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAuthSessionFamily = `-- name: RevokeAuthSessionFamily :exec
UPDATE auth_sessions
SET
    revoked_at = NOW(),
    revocation_reason = $1,
    updated_at = NOW()
WHERE family_id = $2
  AND revoked_at IS NULL
`

type RevokeAuthSessionFamilyParams struct {
	RevocationReason *string   `json:"revocation_reason"`
	FamilyID         uuid.UUID `json:"family_id"`
}

func (q *Queries) RevokeAuthSessionFamily(ctx context.Context, arg RevokeAuthSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionFamily, arg.RevocationReason, arg.FamilyID)
	return err
}
