// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    id,
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    revoked_at,
    created_at,
    updated_at
`

type CreateAuthSessionParams struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	RefreshTokenHash string      `json:"refresh_token_hash"`
	UserAgent        *string     `json:"user_agent"`
	IpAddress        *netip.Addr `json:"ip_address"`
	ExpiresAt        time.Time   `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
SELECT
    id,
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    revoked_at,
    created_at,
    updated_at
FROM auth_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAuthSessionByID(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthSessionsByUserID = `-- name: ListAuthSessionsByUserID :many
SELECT
    id,
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    revoked_at,
    created_at,
    updated_at
FROM auth_sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuthSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listAuthSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSession = `-- name: RevokeAuthSession :one
UPDATE auth_sessions
SET
    revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING
    id,
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at,
    revoked_at,
    created_at,
    updated_at
`

func (q *Queries) RevokeAuthSession(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, revokeAuthSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
