// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        time.Time          `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	Status              string             `json:"status"`
	EmailVerifiedAt     pgtype.Timestamptz `json:"email_verified_at"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}
