// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    status
  )
VALUES ($1, $2, $3, $4)
RETURNING id,
  email,
  password_hash,
  status,
  email_verified_at,
  failed_login_attempts,
  locked_until,
  created_at,
  updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,
  email,
  password_hash,
  status,
  email_verified_at,
  failed_login_attempts,
  locked_until,
  created_at,
  updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
  email,
  password_hash,
  status,
  email_verified_at,
  failed_login_attempts,
  locked_until,
  created_at,
  updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerFailedLogin = `-- name: RegisterFailedLogin :one
UPDATE users
SET
    failed_login_attempts = LEAST(failed_login_attempts + 1, 5),
    locked_until = CASE
        WHEN failed_login_attempts + 1 >= 5
        THEN NOW() + INTERVAL '15 minutes'
        ELSE locked_until
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    email,
    password_hash,
    status,
    email_verified_at,
    failed_login_attempts,
    locked_until,
    created_at,
    updated_at
`

func (q *Queries) RegisterFailedLogin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, registerFailedLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :one
UPDATE users
SET
    failed_login_attempts = 0,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $1
AND failed_login_attempts = $2
AND (locked_until IS NULL OR locked_until <= NOW())
RETURNING
    id,
    email,
    password_hash,
    status,
    email_verified_at,
    failed_login_attempts,
    locked_until,
    created_at,
    updated_at
`

type ResetFailedLoginAttemptsParams struct {
	ID                  uuid.UUID `json:"id"`
	FailedLoginAttempts int32     `json:"failed_login_attempts"`
}

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, arg ResetFailedLoginAttemptsParams) (User, error) {
	row := q.db.QueryRow(ctx, resetFailedLoginAttempts, arg.ID, arg.FailedLoginAttempts)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
